// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbkypURyDF-p-Niep0diTaIJYMsmpten4',
    appId: '1:200838806725:android:3dd43bedcea1ca23d284ac',
    messagingSenderId: '200838806725',
    projectId: 'task-management-952ef',
    storageBucket: 'task-management-952ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBTpuXAEjiXH_nWPUYa1PWYOYlaiSrKx8',
    appId: '1:200838806725:ios:6c55ac9d81eb9410d284ac',
    messagingSenderId: '200838806725',
    projectId: 'task-management-952ef',
    storageBucket: 'task-management-952ef.appspot.com',
    androidClientId: '200838806725-q8ofcstq6e96jp957iibp6kqe1g4fpsb.apps.googleusercontent.com',
    iosClientId: '200838806725-upmgfb7iqbke365lpprv608tgnerfmlh.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskManagementApplication',
  );

}